- name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@2.0.0
  with:
    ftp_server: ${{ secrets.ip }}
    ftp_username: ${{ secrets.username }}
    ftp_password: ${{ secrets.pw }}
    remote_dir: ${{ secrets.dir }}
